font_family JetBrainsMono Nerd Font
font_size 10.0

background #000000
foreground #f5f5f5
background_opacity 0.96
selection_background #f5f5f5
selection_foreground #000000

cursor #f5f5f5
cursor_text_color #000000

color0 #000000
color1 #d0d0d0
color2 #b8b8b8
color3 #c8c8c8
color4 #d8d8d8
color5 #cfcfcf
color6 #bfbfbf
color7 #f5f5f5
color8 #666666
color9 #ffffff
color10 #e0e0e0
color11 #ededed
color12 #f0f0f0
color13 #e5e5e5
color14 #dddddd
color15 #ffffff

window_padding_width 8
confirm_os_window_close 0
enable_audio_bell no
